spring.application.name=alquiler-vehiculos

server.port=8081

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG